services:
  app2:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: project2_app
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db2
    networks:
      - project2_network

  php2:
    build:
      context: ./php
      dockerfile: Dockerfile
    mem_limit: 2g
    container_name: project2_php
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db2
    networks:
      - project2_network

  nginx2:
    image: nginx:latest
    container_name: project2_nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - project2_network

  db2:
    image: mysql:8.0
    container_name: project2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony2
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306"
    volumes:
      - project2_db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - project2_network

networks:
  project2_network:
    driver: bridge

volumes:
  project2_db_data:
